[workspace]
resolver = "2"
members = [
    "crates/remy",
    "crates/remy-core",
    "crates/remy-macros",
    "examples/counter"
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["vyfor"]
description = "An opinionated, reactive framework for Ratatui"
repository = "https://github.com/vyfor/remy"
categories = ["command-line-interface"]
keywords = ["ratatui", "tui", "framework", "reactive", "async"]

[workspace.dependencies]
remy-tui = { path = "crates/remy", version = "0.0.1" }
remy-core = { path = "crates/remy-core", version = "0.0.1" }
remy-macros = { path = "crates/remy-macros", version = "0.0.1" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }
crossterm = { version = "0.29", features = ["event-stream"] }
ratatui = "0.30"
linkme = "0.3"
dashmap = "6"
arc-swap = "1"
futures-util = "0.3"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
