[package]
name = "remy-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "../../README.md"

[dependencies]
tokio = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
linkme = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
futures-util = { workspace = true }
smallvec = "1"
