[package]
name = "remy-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "../../README.md"

[lib]
name = "remy"

[dependencies]
remy-core = { workspace = true }
remy-macros = { workspace = true }
tokio = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
linkme = { workspace = true }
